apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBQhO3D2mT3C93fMXMUVSuoa/dR0H0CYg9bVTEoBnRdauHsKUhzkJRvKMseEZDwj/pU6ke2iZtUlWtcxHRo4QLZSi4K+/df556l1+ll6K5do9U8et/E124TfUfe4RCx2WrQhNKAl9783SRgJ1dAAh6AoZpvm+vLqmSbKCVK5cTiDYO+pyLGKyUpRI5bIk8zMz14ku9HT7gbDUuyP+b8Qf+wDhE7VOHStztAfZwzJTfR84EKVuFK6gyWyq+59xvlza95FBIkWqHrJOECvBdAkNDBSXPmbvFYT0DXl/YcmAH4RTCKYEuCLCt3Sfh61dHwSp3H3rw2lENAAtcps44NT9yg97/DIvBAnwiwDc9hPaWiiSTN4YzteqWeCthcbyruzHzxh3DeABiflls4lEVIjS+4sL/+rqh3x/Mrzxf30VaKHv/I5qu0wO+owneFXsdp46xwasE/8i11JQxObiIOrXXOtFwT07lldI58T50ovbAfnJiGFxb/Qz6bv/Jh2cp/LVsOs6mb3BG+QLE5hx+MNZbJbov8FK+YPkuvuSYVKDmYvcDXijyUZMFBNGNQax59ESGv7e9mmheepZes+whXp6pCCQoSXc4J8aBqRb26UKgkR603a5TWiEkBRtUCdb5WHQFALPzaySQLTqrOXMreDeveESjgUzwXaQbEb/6iDGgnhoNJWQpLfgjfDrY8IAvrKIEPxcZ4ugJJbg==
    username: AgAlHE3vz+jJzW1cx6H1PbyJmll5fG1blD1Y1DDf9q/8U9Z823GsNi6qzL/uqnw9iU/xCZCwpJq7r/vlxkwN01/Shki9r7HuWC5LnDdUvlCL/HjnnIdE9v/kMzbEH+/gJ0dDHAWYNqdVGSpt9YZIk1SWjUePEoljsbsE9tSx9uafBnNQu6b2+uRHMwjF0YsGU/rYYZigLqoEacbBbIGM0CNqXldiCbwv2a7Zvmu8qJM1v1oETMpN5JIr+qHQDb/eU9bPhfphxY28T7y9OkYa3Am0KK4Eq4Id17IfVt1vwnDN//a+sRszCCM/fXmXcL74rl1raBNUDPLj4YQskxTC69tJB5XUbEhoF5fFGrwF66fALsFuCDjZ5+jkP4R8heQej5AxE+eJMtb+PJbD5PC7qzZN8rUM8a16BUgIj8o+ndiBqiI77U6+yvVhx8p6v1TijDHhofSeHMB/d8zabEAE+G3OssueNGtDZTbpki4VEf0VVcz9B4iGyEMRwDjI+SLUj9vv90Y0A0kaD02DkD3qe9jP2hTJfaLFGAwkeOCtrAfiCjbjuNCg1wsvPRrJc0ZyrKjGXUH8yUE5JJZu381ZCeiiFbRhessZl4YRId97OJWVJWW/RXgdLsidmDuCPynAFtBlZqpkoWMnsRVb8V3uupZhCbmx4mPa6h3QNb1HuMFLh+Mg5bvcCe2f6IndhzDipYuKj7da4Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: default
    type: Opaque

